### PR TITLE
Complete quick fix the onSubmit function

### LINKED ISSUE #27: Quick fix the post request pending
# Description

-

### PR DESCRIPTION
**Pull request by anthonyminyungi**
# Description

- It fixes #27 

-

### CODE REVIEW

File: packages/keyda-demo/src/lib/FormToSubmit/index.js [hunk 1]
```diff
@@ -27,16 +27,17 @@ const FormToSubmit = (props) => {
...
-        });
+      (async () => {
+        const dataToSubmit = {
+          keyTimeList: keyState.keyTimeList,
+          userId: keyState.userId,
+        };
+        console.log(dataToSubmit);
+        const request = await axios
+          .post(REQUEST_URL + suffix, dataToSubmit)
+          .then((response) => response);
```
Comment (anthonyminyungi) [inline packages/keyda-demo/src/lib/FormToSubmit/index.js:38]: I changed the logic of post request to our server into IIFE(immediately invoked function expression) to use `async/await` keyword for the proper access to the server.
